from typing import Any, Callable
from datetime import datetime
import re as _re
import uuid as _uuid
import time as ttime
from typing import Dict, Iterable, Optional
from bluesky.utils import msg_to_json_safe_dict

# ----------------------------------------------------------------------------------
# Small formatting helpers
# ----------------------------------------------------------------------------------

def _fmt_timestamp(t: float | None) -> str:
    """Format an epoch timestamp as a human-readable local wall-clock time with ms."""
    if t is None:
        return "--:--:--"
    try:
        dt = datetime.fromtimestamp(t)
    except (OverflowError, OSError, ValueError):
        return str(t)
    return f"{dt:%H:%M:%S}.{dt.microsecond // 1000:03d}"

def _fmt_value(value: Any) -> str:
    """Format an argument value for prose (compact, readable)."""
    if value is None:
        return "nothing"
    if isinstance(value, bool):
        return "on" if value else "off"
    if isinstance(value, float):
        # Trim noisy trailing zeros without losing meaningful precision.
        text = f"{value:.6g}"
        return text
    if isinstance(value, str):
        return f"'{value}'" if value else "''"
    if isinstance(value, (list, tuple)):
        inner = ", ".join(_fmt_value(v) for v in value)
        return f"[{inner}]"
    if isinstance(value, dict):
        inner = ", ".join(f"{k}={_fmt_value(v)}" for k, v in value.items())
        return f"{{{inner}}}"
    return str(value)


def _fmt_obj(obj: str | None) -> str:
    """Format a device/object name."""
    if not obj:
        return "the device"
    return f"'{obj}'"


def _fmt_kwargs(kwargs: dict[str, Any], *, skip: Iterable[str] = ()) -> str:
    """Format kwargs into a trailing clause, skipping bookkeeping keys like 'group'."""
    skip = set(skip)
    items = {k: v for k, v in (kwargs or {}).items() if k not in skip}
    if not items:
        return ""
    parts = [f"{k}={_fmt_value(v)}" for k, v in items.items()]
    return " with " + ", ".join(parts)


def _join_names(items: Iterable[str]) -> str:
    """Join pre-formatted phrases into an English list with an Oxford comma."""
    items = list(items)
    if not items:
        return ""
    if len(items) == 1:
        return items[0]
    if len(items) == 2:
        return f"{items[0]} and {items[1]}"
    return ", ".join(items[:-1]) + f", and {items[-1]}"


class GroupLabeler:
    """
    Maps bluesky group ids to friendly labels for narration. Auto-generated ids (random
    UUIDs, as ``mv``/``abs_set``/``stage_all`` create by default) are named after the
    *command* that opened the group -- e.g. a ``stage_all`` group becomes ``stage`` and a
    ``kickoff_all`` group becomes ``kickoff``. If more than one auto group for the same
    command is open at once, later ones are disambiguated with a number (``stage 2``).
    Group names the user chose explicitly (e.g. ``abs_set(motor, 1, group="align")``) are
    recognized as non-random and preserved verbatim.

    ``label`` returns the bare token (``stage``, ``stage 2``, ``align``); callers add the
    surrounding wording (e.g. ``f"group '{label}'"``).
    """

    # bluesky auto group ids are ``str(uuid4())`` or its 32-char hex form.
    _HEX32 = _re.compile(r"\A[0-9a-fA-F]{32}\Z")

    def __init__(self) -> None:
        self._labels: dict[str, str] = {}
        self._active: dict[str, int] = {}  # base command -> count of currently-open groups
        self._auto: set = set()            # group ids that were auto-generated

    @classmethod
    def _looks_autogenerated(cls, group: str) -> bool:
        try:
            _uuid.UUID(group)
            return True
        except (ValueError, AttributeError, TypeError):
            return bool(cls._HEX32.match(group)) if isinstance(group, str) else False

    def label(self, group: str | None, command: str | None = None) -> str | None:
        if group is None:
            return None
        if group not in self._labels:
            if self._looks_autogenerated(group):
                base = command or "group"
                active = self._active.get(base, 0) + 1
                self._active[base] = active
                self._labels[group] = base if active == 1 else f"{base} {active}"
                self._auto.add(group)
            else:
                # Preserve a user-chosen group name verbatim.
                self._labels[group] = group
        return self._labels[group]

    def release(self, group: str | None) -> None:
        """Mark an auto group as closed so its command name is free to reuse without a number."""
        if group is None or group not in self._auto:
            return  # unknown or user-named group: nothing to release
        label = self._labels.get(group)
        if not label:
            return
        base = label.rsplit(" ", 1)[0] if label[-1:].isdigit() else label
        if self._active.get(base):
            self._active[base] -= 1


# ----------------------------------------------------------------------------------
# Per-command describers
# ----------------------------------------------------------------------------------

def _group_clause(msg: dict[str, Any], groups: "GroupLabeler") -> str:
    """Trailing ', as part of group X' clause, or '' when the message carries no group."""
    label = groups.label((msg.get("kwargs") or {}).get("group"), msg.get("command"))
    return f", as part of group '{label}'" if label else ""


def _fmt_prepare_value(value: Any) -> str:
    """
    Describe a ``prepare`` value (usually a dataclass) as a compact parameter phrase.

    The value has already been serialized, so a dataclass typically arrives either as a
    dict of its fields or as its ``repr`` string (e.g. ``TriggerInfo(number=1801, ...)``).
    """
    if value is None:
        return ""
    if isinstance(value, dict):
        return ", ".join(f"{k}={_fmt_value(v)}" for k, v in value.items())
    if isinstance(value, (list, tuple)):
        return _fmt_value(value)
    return str(value).strip()


def _describe(msg: dict[str, Any], groups: "GroupLabeler") -> str:
    """Return the sentence for a single serialized message."""
    command = msg.get("command")
    obj = _fmt_obj(msg.get("obj"))
    args = msg.get("args") or []
    kwargs = msg.get("kwargs") or {}

    match command:
        case "set":
            target = _fmt_value(args[0]) if args else "a new value"
            return f"Setting {obj} to {target}{_group_clause(msg, groups)}."
        case "trigger":
            return f"Triggering {obj}{_group_clause(msg, groups)}."
        case "read":
            return f"Reading the current value of {obj}."
        case "wait":
            group = groups.label(kwargs.get("group"))
            if group:
                return f"Waiting for group '{group}' to finish."
            return "Waiting for pending operations to complete."
        case "sleep":
            if args:
                return f"Pausing for {_fmt_value(args[0])} seconds."
            return "Pausing briefly."
        case "checkpoint":
            return "Marking a checkpoint (a safe point to pause or resume)."
        case "clear_checkpoint":
            return "Clearing the current checkpoint (pausing here is no longer safe)."
        case "create":
            name = kwargs.get("name")
            stream = f" for stream '{name}'" if name else ""
            return f"Beginning a new data reading{stream}."
        case "save":
            return "Saving the collected readings as a data point."
        case "drop":
            return "Discarding the current in-progress data point."
        case "open_run":
            plan_name = kwargs.get("plan_name")
            scan_id = kwargs.get("scan_id")
            bits = []
            if plan_name:
                bits.append(f"plan '{plan_name}'")
            if scan_id is not None:
                bits.append(f"scan id {scan_id}")
            detail = (" (" + ", ".join(bits) + ")") if bits else ""
            return f"Starting a new run{detail}."
        case "close_run":
            exit_status = kwargs.get("exit_status")
            if exit_status:
                return f"Closing the run ({exit_status})."
            return "Closing the current run."
        case "stage":
            return f"Staging {obj} for data collection{_group_clause(msg, groups)}."
        case "unstage":
            return f"Unstaging {obj}{_group_clause(msg, groups)}."
        case "monitor":
            return f"Starting to monitor {obj} for asynchronous updates{_group_clause(msg, groups)}."
        case "unmonitor":
            return f"Stopping monitoring of {obj}{_group_clause(msg, groups)}."
        case "configure":
            tail = _fmt_kwargs(kwargs, skip=("group",))
            return f"Configuring {obj}{tail}{_group_clause(msg, groups)}."
        case "subscribe":
            return "Attaching a callback to receive documents."
        case "unsubscribe":
            return "Detaching a previously attached callback."
        case "kickoff":
            return f"Kicking off flyscan with {obj}{_group_clause(msg, groups)}."
        case "complete":
            return f"Waiting flyscan with {obj} to complete{_group_clause(msg, groups)}."
        case "collect":
            return f"Collecting buffered data from {obj}{_group_clause(msg, groups)}."
        case "declare_stream":
            return "Declaring the structure of a data stream."
        case "stop":
            return f"Stopping {obj}."
        case "locate":
            return f"Locating the current position of {obj}."
        case "prepare":
            params = _fmt_prepare_value(args[0]) if args else ""
            with_clause = f" with {params}" if params else ""
            return f"Preparing {obj} for the next step{with_clause}{_group_clause(msg, groups)}."
        case "pause":
            return "Pausing the plan."
        case "resume":
            return "Resuming the plan."
        case "null":
            return "Doing nothing (no-op)."
        case "wait_for":
            return "Waiting for one or more external tasks to complete."
        case _:
            # Unknown/rare commands: state it plainly using whatever we have.
            where = f" on {obj}" if msg.get("obj") else ""
            pretty = str(command).replace("_", " ") if command else "an operation"
            return f"Performing '{pretty}'{where}."


def describe_message(
    msg: dict[str, Any],
    *,
    groups: GroupLabeler | None = None,
    show_timestamps: bool = False,
) -> str:
    """
    Convert a single serialized RunEngine message into a natural-language sentence.

    Parameters
    ----------
    msg : dict
        A serialized message (see module docstring for the shape).
    groups : GroupLabeler, optional
        Shared labeler so group ids are named consistently across a stream. A fresh
        one is created if not supplied.
    show_timestamps : bool, optional
        If True, prefix the sentence with the message's human-readable timestamp,
        e.g. ``[14:30:45.123] Setting 'motor' to 1.``.

    Returns
    -------
    str
        A human-readable, best-effort description of the message.
    """
    sentence = _describe(msg, groups or GroupLabeler())

    if show_timestamps:
        return f"[{_fmt_timestamp(msg.get('time'))}] {sentence}"
    return sentence


# ----------------------------------------------------------------------------------
# Stream-level narration (collapses common multi-message patterns)
# ----------------------------------------------------------------------------------

# Commands whose messages each target a single object and naturally arrive back-to-back
# (one per device). Consecutive messages of the same command are merged into one line,
# but only when they share the same group (see StreamNarrator). Each entry returns the
# sentence *core* (no trailing period and no group clause); the group clause -- and, for
# ``prepare``, the shared value -- are appended by StreamNarrator._flush_batch.
_BATCH_PHRASES = {
    "read": lambda names: (
        f"Reading the current value of {names[0]}"
        if len(names) == 1
        else f"Reading the current values of {_join_names(names)}"
    ),
    "stage": lambda names: f"Staging {_join_names(names)} for data collection",
    "unstage": lambda names: f"Unstaging {_join_names(names)}",
    "monitor": lambda names: f"Starting to monitor {_join_names(names)} for asynchronous updates",
    "unmonitor": lambda names: f"Stopping monitoring of {_join_names(names)}",
    "kickoff": lambda names: (
        f"Kicking off the flyer {names[0]} (starting a fly-scan)"
        if len(names) == 1
        else f"Kicking off the flyers {_join_names(names)} (starting a fly-scan)"
    ),
    "complete": lambda names: (
        f"Waiting for the flyer {names[0]} to finish flying"
        if len(names) == 1
        else f"Waiting for the flyers {_join_names(names)} to finish flying"
    ),
    "collect": lambda names: f"Collecting buffered data from {_join_names(names)}",
    "prepare": lambda names: f"Preparing {_join_names(names)} for the next step",
}


def narrate_stream(
    messages: Iterable[dict[str, Any]],
    *,
    show_timestamps: bool = False,
    window: float = 60.0,
) -> list[str]:
    """
    Convert a whole sequence of serialized messages into a list of natural-language
    lines, collapsing common multi-message patterns into single sentences:

    * one or more ``set`` messages sharing a group, followed by a ``wait`` on that group
      (what ``mv``/``mvr`` emit) -> a single "Moving ..." sentence;
    * one or more ``trigger`` messages sharing a group, followed by a ``wait`` (what
      triggering a list of detectors emits) -> a single "Triggering ..." sentence;
    * a run of consecutive same-command messages that target one device each -- ``read``,
      ``stage``, ``unstage``, ``monitor``, ``unmonitor`` -> a single combined sentence.

    Messages are only joined while they fall within ``window`` seconds of the start of
    the run (see :class:`StreamNarrator`). This is a convenience wrapper over
    :class:`StreamNarrator` for the case where the full sequence is already available.

    Parameters
    ----------
    messages : iterable of dict
        Serialized messages, in the order they were processed.
    show_timestamps : bool, optional
        If True, prefix each line with the human-readable timestamp of the message that
        produced it (for a collapsed line, the time of the first message in the group).
    window : float, optional
        Maximum span, in seconds, over which same-kind messages are joined.

    Returns
    -------
    list of str
        Human-readable narration lines.
    """
    narrator = StreamNarrator(show_timestamps=show_timestamps, window=window)
    lines: list[str] = []
    for msg in messages:
        lines.extend(narrator.push(msg))
    lines.extend(narrator.flush())
    return lines


class StreamNarrator:
    """
    Incremental narrator for a *live* message stream consumed one message at a time.

    Messages of the same collapsible kind are joined into a single line, but only while
    they fall within ``window`` seconds of the start of the current run. A pending line
    is flushed (returned to the caller) as soon as:

    * a message of a different kind arrives, or
    * the time window elapses -- either because an incoming message is more than
      ``window`` seconds after the run started (handled in :meth:`push`), or because
      :meth:`due` is called after a period of inactivity.

    All methods return a list of finalized narration lines (possibly empty). Typical
    use with a blocking consumer::

        narrator = StreamNarrator(show_timestamps=True)
        while True:
            msg = queue.get(timeout=5)          # or however messages arrive
            if msg is not None:
                for line in narrator.push(msg):
                    print(line)
            for line in narrator.due():          # flush stale lines while idle
                print(line)
        # at shutdown:
        for line in narrator.flush():
            print(line)

    Parameters
    ----------
    show_timestamps : bool, optional
        Prefix each line with the human-readable timestamp of the message that produced
        it (for a collapsed line, the time of the first message in the run).
    window : float, optional
        Maximum span, in seconds, over which same-kind messages are joined. Defaults to
        60 seconds.
    """

    def __init__(self, *, show_timestamps: bool = False, window: float = 60.0) -> None:
        self._show_timestamps = show_timestamps
        self._window = float(window)
        self._groups = GroupLabeler()
        # At most one of {batch, groups} is ever open (starting one flushes the other).
        self._batch_cmd: str | None = None
        self._batch_msgs: list[dict[str, Any]] = []
        self._batch_group: str | None = None  # shared group of the open batch (or None)
        self._batch_value: Any = None            # shared `prepare` value of the open batch
        # Pending `set`/`trigger` messages awaiting a matching `wait`, keyed by group id.
        self._pending_group: dict[str, list[dict[str, Any]]] = {}
        self._group_order: list[str] = []  # arrival order of open groups

    # -- formatting ------------------------------------------------------------

    def _line(self, msg: dict[str, Any], text: str | None = None) -> str:
        text = text if text is not None else describe_message(msg, groups=self._groups)
        if self._show_timestamps:
            text = f"[{_fmt_timestamp(msg.get('time'))}] {text}"
        return text

    @staticmethod
    def _span_exceeded(msgs: list[dict[str, Any]], t: float | None, window: float) -> bool:
        """True if ``t`` is more than ``window`` seconds after the run's first message."""
        if not msgs or t is None:
            return False
        start = msgs[0].get("time")
        return start is not None and (t - start) > window

    # -- flush helpers (each returns a list of finalized lines) ----------------

    def _flush_batch(self) -> list[str]:
        out: list[str] = []
        if self._batch_msgs:
            # Unique object names, preserving first-seen order.
            names: list[str] = []
            seen = set()
            for m in self._batch_msgs:
                name = _fmt_obj(m.get("obj"))
                if name not in seen:
                    seen.add(name)
                    names.append(name)
            core = _BATCH_PHRASES[self._batch_cmd](names)
            if self._batch_cmd == "prepare":
                params = _fmt_prepare_value(self._batch_value)
                if params:
                    core += f" with {params}"
            if self._batch_group is not None:
                label = self._groups.label(self._batch_group, self._batch_cmd)
                core += f", as part of group '{label}'"
            out.append(self._line(self._batch_msgs[0], core + "."))
        self._batch_cmd, self._batch_msgs = None, []
        self._batch_group, self._batch_value = None, None
        return out

    def _flush_group(self, group_id: str) -> list[str]:
        # A group that never saw its `wait`: describe its messages plainly.
        out = [self._line(m) for m in self._pending_group.pop(group_id, [])]
        if group_id in self._group_order:
            self._group_order.remove(group_id)
        return out

    def _flush_all_groups(self) -> list[str]:
        out: list[str] = []
        for gid in list(self._group_order):
            out.extend(self._flush_group(gid))
        return out

    def _complete_group(self, msgs: list[dict[str, Any]]) -> list[str]:
        # A group closed by its `wait`: collapse into a single "Moving"/"Triggering" line.
        pronoun = "it" if len(msgs) == 1 else "them"
        group_id = (msgs[0].get("kwargs") or {}).get("group")
        label = self._groups.label(group_id, msgs[0].get("command"))
        clause = f", as part of group '{label}'" if label else ""
        if all(m.get("command") == "set" for m in msgs):
            moves = []
            for m in msgs:
                args = m.get("args") or []
                target = _fmt_value(args[0]) if args else "a new value"
                moves.append(f"{_fmt_obj(m.get('obj'))} to {target}")
            return [self._line(msgs[0], f"Moving {_join_names(moves)} and waiting for {pronoun} to arrive{clause}.")]
        if all(m.get("command") == "trigger" for m in msgs):
            names = [_fmt_obj(m.get("obj")) for m in msgs]
            return [self._line(msgs[0], f"Triggering {_join_names(names)} and waiting for {pronoun} to complete{clause}.")]
        # Mixed group: describe each action, then note the wait.
        out = [self._line(m) for m in msgs]
        out.append(self._line(msgs[-1], f"Waiting for group '{label}' to finish." if label else "Waiting for the group to complete."))
        return out

    # -- public API ------------------------------------------------------------

    def push(self, msg: dict[str, Any]) -> list[str]:
        """Consume one serialized message; return any finalized narration lines."""
        command = msg.get("command")
        kwargs = msg.get("kwargs") or {}
        group_id = kwargs.get("group")
        t = msg.get("time")
        out: list[str] = []

        if command in _BATCH_PHRASES:
            out.extend(self._flush_all_groups())  # a batch ends any pending group
            value = (msg.get("args") or [None])[0] if command == "prepare" else None
            # Join only same-command messages that share the same group (and, for
            # `prepare`, the same value) and fall within the time window.
            joinable = (
                self._batch_cmd == command
                and self._batch_group == group_id
                and (command != "prepare" or self._batch_value == value)
                and not self._span_exceeded(self._batch_msgs, t, self._window)
            )
            if joinable:
                self._batch_msgs.append(msg)
            else:
                out.extend(self._flush_batch())
                self._batch_cmd, self._batch_msgs = command, [msg]
                self._batch_group, self._batch_value = group_id, value
            return out

        if command in ("set", "trigger") and group_id is not None:
            out.extend(self._flush_batch())
            existing = self._pending_group.get(group_id)
            if existing and self._span_exceeded(existing, t, self._window):
                out.extend(self._flush_group(group_id))
            if group_id not in self._pending_group:
                self._pending_group[group_id] = []
                self._group_order.append(group_id)
            self._pending_group[group_id].append(msg)
            return out

        if command == "wait" and group_id is not None and group_id in self._pending_group:
            out.extend(self._flush_batch())
            msgs = self._pending_group.pop(group_id)
            self._group_order.remove(group_id)
            out.extend(self._complete_group(msgs))
            self._groups.release(group_id)
            return out

        # Any other message: flush pending buffers first so ordering stays truthful.
        out.extend(self._flush_batch())
        out.extend(self._flush_all_groups())
        out.append(self._line(msg))
        if command == "wait" and group_id is not None:
            self._groups.release(group_id)
        return out

    def due(self, now: float | None = None) -> list[str]:
        """
        Flush any open batch/group that has been idle (no new message) for longer than
        ``window`` seconds, using ``now`` (defaults to the current wall-clock time) as
        the reference. Call periodically while waiting for the next message so a run of
        similar messages does not stay buffered indefinitely on a quiet stream.
        """
        if now is None:
            now = ttime.time()
        out: list[str] = []

        if self._batch_msgs:
            last = self._batch_msgs[-1].get("time")
            if last is not None and (now - last) > self._window:
                out.extend(self._flush_batch())

        for gid in list(self._group_order):
            msgs = self._pending_group.get(gid, [])
            last = msgs[-1].get("time") if msgs else None
            if last is not None and (now - last) > self._window:
                out.extend(self._flush_group(gid))

        return out

    def flush(self) -> list[str]:
        """Flush all pending buffers (call at end of stream)."""
        out = self._flush_batch()
        out.extend(self._flush_all_groups())
        return out


# ----------------------------------------------------------------------------------
# RunEngine msg_hook
# ----------------------------------------------------------------------------------

class MsgHookNarrator:
    """
    A bluesky ``RunEngine`` ``msg_hook`` that narrates a plan's activity in plain English.

    Attach an instance to a RunEngine and it will, for every ``Msg`` the RunEngine
    processes, serialize the message, feed it to a :class:`StreamNarrator`, and emit any
    finalized narration lines (printed by default)::

        RE.msg_hook = MsgHookNarrator()

    By default the hook consumes *raw* ``Msg`` objects and serializes them itself. If you
    are feeding it messages that are already serialized (dicts of the documented shape),
    pass ``serialize=False``.

    Parameters
    ----------
    emit : callable, optional
        Called with each finalized narration line (a ``str``). Defaults to :func:`print`.
    show_timestamps : bool, optional
        Prefix each line with the message's human-readable timestamp.
    window : float, optional
        Maximum span, in seconds, over which same-kind messages are joined (see
        :class:`StreamNarrator`).
    serialize : bool, optional
        If True (default), incoming values are treated as raw ``Msg`` objects and
        serialized via :func:`serialize_msg`. If False, they are assumed to already be
        serialized dicts.
    """

    def __init__(
        self,
        *,
        emit: Callable[[str], Any] | None = None,
        show_timestamps: bool = False,
        window: float = 60.0,
        serialize: bool = True,
    ) -> None:
        self._emit = emit if emit is not None else print
        self._serialize = serialize
        self._narrator = StreamNarrator(show_timestamps=show_timestamps, window=window)
        self._listeners: list[Callable[[str], Any]] = []

    def add_listener(self, callback: Callable[[str], Any]) -> None:
        """Also send each finalized line to ``callback`` (called on the RunEngine thread)."""
        self._listeners.append(callback)

    def remove_listener(self, callback: Callable[[str], Any]) -> None:
        if callback in self._listeners:
            self._listeners.remove(callback)

    def _send(self, line: str) -> None:
        self._emit(line)
        for listener in list(self._listeners):
            try:
                listener(line)
            except Exception:
                # A broken listener must not fail the running plan.
                pass

    def __call__(self, msg: Any) -> None:
        """Consume one message (raw ``Msg`` by default); emit any finalized lines."""
        record = msg_to_json_safe_dict(msg) if self._serialize else msg
        for line in self._narrator.push(record):
            self._send(line)

    def due(self, now: float | None = None) -> None:
        """Emit any lines whose buffered run has been idle longer than ``window`` seconds."""
        for line in self._narrator.due(now):
            self._send(line)

    def flush(self) -> None:
        """Emit all remaining buffered lines (call when the plan/stream ends)."""
        for line in self._narrator.flush():
            self._send(line)


#: Ready-to-use natural-language ``msg_hook`` instance: ``RE.msg_hook = nl_msg_hook``.
nl_msg_hook = MsgHookNarrator()


# ----------------------------------------------------------------------------------
# Demo
# ----------------------------------------------------------------------------------

# if __name__ == "__main__":
#     # Example stream resembling reading several detectors, with a mix of an
#     # auto-generated group (UUID) and a user-named group ("align").
#     example_stream = [
#         {"time": 0.0, "command": "open_run", "obj": None, "args": [],
#          "kwargs": {"plan_name": "scan", "scan_id": 3}, "run": None},
#         {"time": 0.0, "command": "stage", "obj": "det1", "args": [], "kwargs": {}, "run": None},
#         {"time": 0.0, "command": "set", "obj": "motor", "args": [0],
#          "kwargs": {"group": "align"}, "run": None},
#         {"time": 0.0, "command": "wait", "obj": None, "args": [],
#          "kwargs": {"group": "align"}, "run": None},
#         {"time": 0.0, "command": "create", "obj": None, "args": [], "kwargs": {"name": "primary"}, "run": None},
#         {"time": 0.0, "command": "trigger", "obj": "det1", "args": [],
#          "kwargs": {"group": "trigger"}, "run": None},
#         {"time": 0.0, "command": "trigger", "obj": "det2", "args": [],
#          "kwargs": {"group": "trigger"}, "run": None},
#         {"time": 0.0, "command": "wait", "obj": None, "args": [],
#          "kwargs": {"group": "trigger"}, "run": None},
#         {"time": 0.0, "command": "read", "obj": "det1", "args": [], "kwargs": {}, "run": None},
#         {"time": 0.0, "command": "read", "obj": "det2", "args": [], "kwargs": {}, "run": None},
#         {"time": 0.0, "command": "read", "obj": "motor", "args": [], "kwargs": {}, "run": None},
#         {"time": 0.0, "command": "save", "obj": None, "args": [], "kwargs": {}, "run": None},
#         {"time": 0.0, "command": "set", "obj": "motor", "args": [1],
#          "kwargs": {"group": "a1b2c3d4-e5f6-4718-a93a-4b5c6d7e8f90"}, "run": None},
#         {"time": 0.0, "command": "wait", "obj": None, "args": [],
#          "kwargs": {"group": "a1b2c3d4-e5f6-4718-a93a-4b5c6d7e8f90"}, "run": None},
#         {"time": 0.0, "command": "unstage", "obj": "det1", "args": [], "kwargs": {}, "run": None},
#         {"time": 0.0, "command": "unstage", "obj": "det2", "args": [], "kwargs": {}, "run": None},
#         {"time": 0.0, "command": "close_run", "obj": None, "args": [],
#          "kwargs": {"exit_status": "success"}, "run": None},
#     ]

#     # Assign increasing wall-clock timestamps so the human-readable times are meaningful.
#     _base = _time.time()
#     for _i, _m in enumerate(example_stream):
#         _m["time"] = _base + _i * 0.5

#     print("=== describe_message (one line per raw message) ===")
#     _groups = GroupLabeler()
#     for m in example_stream:
#         print(" -", describe_message(m, groups=_groups))

#     print("\n=== narrate_stream (collapsed / friendlier) ===")
#     for line in narrate_stream(example_stream):
#         print(" -", line)

#     print("\n=== narrate_stream with timestamps ===")
#     for line in narrate_stream(example_stream, show_timestamps=True):
#         print(" -", line)

#     # --- Live streaming demo: consume one message at a time with a short window. ---
#     # Three reads arrive close together, then a 4th read arrives after a long gap, so
#     # the window splits it into a separate line even though it is the same command.
#     print("\n=== StreamNarrator (live, window=10s) ===")
#     _t0 = _time.time()
#     live_stream = [
#         {"time": _t0 + 0.0, "command": "read", "obj": "det1", "args": [], "kwargs": {}, "run": None},
#         {"time": _t0 + 1.0, "command": "read", "obj": "det2", "args": [], "kwargs": {}, "run": None},
#         {"time": _t0 + 2.0, "command": "read", "obj": "det3", "args": [], "kwargs": {}, "run": None},
#         # ... long pause (> window) ...
#         {"time": _t0 + 45.0, "command": "read", "obj": "det4", "args": [], "kwargs": {}, "run": None},
#         {"time": _t0 + 46.0, "command": "save", "obj": None, "args": [], "kwargs": {}, "run": None},
#     ]
#     narrator = StreamNarrator(show_timestamps=True, window=10.0)
#     for _m in live_stream:
#         for _line in narrator.push(_m):
#             print(" -", _line)
#     for _line in narrator.flush():
#         print(" -", _line)

#     # --- msg_hook demo: feed *raw* Msg objects; the hook serializes them itself. ---
#     # Simulates `RE.msg_hook = MsgHookNarrator()` running over a tiny plan. Devices are
#     # serialized via repr(), so their type shows up in the narration.
#     from collections import namedtuple

#     _Msg = namedtuple("Msg", ["command", "obj", "args", "kwargs", "run"])

#     class _DemoMotor:
#         def __init__(self, name):
#             self.name = name

#         def __repr__(self):
#             return f"EpicsMotor(name={self.name!r})"

#     def _raw(command, obj=None, args=(), kwargs=None, run=None):
#         return _Msg(command, obj, args, kwargs or {}, run)

#     _motor = _DemoMotor("theta")
#     raw_plan = [
#         _raw("open_run", kwargs={"plan_name": "rel_scan", "scan_id": 7}),
#         _raw("stage", _motor),
#         _raw("set", _motor, args=(90,), kwargs={"group": "move-1"}),
#         _raw("wait", kwargs={"group": "move-1"}),
#         _raw("trigger", _DemoMotor("det"), kwargs={"group": "trig"}),
#         _raw("wait", kwargs={"group": "trig"}),
#         _raw("unstage", _motor),
#         _raw("close_run", kwargs={"exit_status": "success"}),
#     ]

#     print("\n=== MsgHookNarrator (raw Msg -> serialized -> narration) ===")
#     hook = MsgHookNarrator(emit=lambda s: print(" -", s))
#     for _m in raw_plan:  # this is exactly what RE.msg_hook would receive
#         hook(_m)
#     hook.flush()

