name: Publish Release to PyPI
permissions:
  contents: read

on:
  release:
    types:
      - published

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@2253d9c9310442c09975d64615591b5b381da6e7  # v0.10.0
        with:
          environments: dev

      - name: Build sdist and wheel
        run: >
          export SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct) &&
          pixi run --as-is -e dev python -m build

      - name: Upload sdist and wheel as artifacts
        uses: actions/upload-artifact@v7
        with:
          name: dist
          path: dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Install produced wheel
        run: |
          pixi run --as-is -e dev pip install dist/*.whl --force-reinstall --no-deps

      - name: Verify installation
        run: |
          pixi run --as-is -e dev python -m hextools --version
